kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80    # Maps container port 80 to host port 8080
        hostPort: 8080
        protocol: TCP
      - containerPort: 443   # Maps container port 443 to host port 8443
        hostPort: 8443
        protocol: TCP
  - role: worker
  - role: worker
  - role: worker