global:
  istioNamespace: istio-ingress

name: istio-ingressgateway

image:
  repository: docker.io/istio/proxyv2
  tag: 1.26.0

resources:
  requests:
    cpu: 10m
    memory: 128Mi
  limits:
    cpu: 2000m
    memory: 2024Mi

podDisruptionBudget:
  enabled: true
  maxUnavailable: 1

autoscaling:
  enabled: true

service:
  type: LoadBalancer
  # annotations:
  #   cloud.google.com/load-balancer-type: "Internal"
  #   networking.gke.io/internal-load-balancer-allow-global-access: "true"
  #   cloud.google.com/backend-config: '{"default": "istio-ingress-backendconfig"}'