redis-ha:
  enabled: false

controller:
  replicas: 1

server:
  autoscaling:
    enabled: false
    minReplicas: 1

repoServer:
  autoscaling:
    enabled: false
    minReplicas: 1

applicationSet:
  replicas: 1